# Generated by Django 3.1.3 on 2020-12-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('num_tel', models.IntegerField()),
                ('school', models.CharField(choices=[('Al Khwarizmi', 'Al Khawarizmi'), ('FGSES', 'FGSES'), ('EMINES', 'EMINES'), ('ABS', 'ABS'), ('SCI', 'SCI'), ('SHBM', 'SHBM'), ('SAP+D', 'SAP+D'), ('CBS/GPE', 'CBS/GPE'), ('MSN', 'MSN'), ('GTI', 'GTI'), ('GSM', 'GSM'), ('CIAM', 'CIAM'), ('1337', '1337'), ('MAHIR', 'MAHIR')], max_length=250)),
                ('first_participant', models.CharField(blank=True, max_length=100, null=True)),
                ('second_participant', models.CharField(blank=True, max_length=100, null=True)),
                ('third_participant', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.CharField(max_length=100)),
                ('theme', models.CharField(choices=[('Education', 'Education'), ('Mental Health And Wellness', 'Mental Health And Wellness'), ('Student Organizations And Events', 'Student Organizations And Events')], max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
