# Generated by Django 3.1.3 on 2020-12-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='theme',
            field=models.CharField(blank=True, choices=[('Education', 'Education'), ('Mental Health And Wellness', 'Mental Health And Wellness'), ('Student Organizations And Events', 'Student Organizations And Events')], max_length=250, null=True),
        ),
    ]
